Update CSS token per new design system theming capability
AlaskaAirlines/auro-card pull request #48
Opened 2023-11-08 09:11 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

**Fixes:** #47 

## Summary:

- Update the design tokens to reflect the new theming conventions regarding tokens from the AuroDesignTokens and JetstreamDesignTokens repo.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-08 09:18 UTC, fajar-apri-alaska commented
Hi @jason-capsule42 or @blackfalcon.
I'm not sure how to fix this `npm ci` error for `node 11` [in this pipeline error.](https://github.com/AlaskaAirlines/auro-card/actions/runs/6796061012/job/18475370018?pr=48#step:4:97)

Please advise.

FYI some references:
https://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected

2023-11-08 16:46 UTC, jason-capsule42 requested changes
Tests are failing here. Please check whythat is.

2023-11-10 03:53 UTC, blackfalcon requested changes

2023-11-10 03:53 UTC, blackfalcon commented on demo/index.html
> +      // import "https://unpkg.com/prismjs@latest/prism.js";
Please see https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/demo/index.html for the correct configuration. 

Also, please remove commented code when prepared for PR review.

2023-11-10 03:53 UTC, blackfalcon commented on package.json
>      "@alaskaairux/design-tokens": "^3.1.0",
Remove

2023-11-10 03:53 UTC, blackfalcon commented on src/style-banner.scss
> +@import "./../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SassCustomProperties";
```suggestion
```

2023-11-10 03:53 UTC, blackfalcon commented on src/style-banner.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables.scss';
```suggestion
```

2023-11-10 03:53 UTC, blackfalcon commented on src/style.scss
> +@import "./../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SassCustomProperties";
```suggestion
```

2023-11-10 08:31 UTC, fajar-apri-alaska commented
I have pushed some more changes per feedback above.

2023-12-26 22:32 UTC, jordanjones243 approved these changes

2023-12-26 22:33 UTC, jordanjones243 requested changes
Tests are failing. Support for Node 11 needs to be removed from the repo.

2024-01-21 21:24 UTC, jordanjones243 commented
Closing this PR as the work was handled in a different PR:
- https://github.com/AlaskaAirlines/auro-card/pull/52

2024-01-21 21:24 UTC, closed without merging