docs(images): update path of images
AlaskaAirlines/auro-card pull request #61
Opened 2024-05-02 20:43 UTC by braven112

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #60 

## Summary:

Updated all the image references.

## Type of change:

Please delete options that are not relevant.

- [x] Other (Demo image url update)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-05-03 19:25 UTC, jordanjones243 approved these changes

2024-05-07 22:40 UTC, blackfalcon requested changes
This PR has issues and is unnecessary due to the soon to be released version.

2024-05-07 22:40 UTC, blackfalcon commented on CHANGELOG.md
> +
Why was the changelog added to this PR?

2024-05-07 22:40 UTC, blackfalcon commented on README.md
> +<script src="https://cdn.jsdelivr.net/npm/@aurodesignsystem/auro-card@2.0.4/dist/auro-card__bundled.js" type="module"></script>
This README update is something that happens in the remote, why was this added to the PR?

2024-05-07 22:40 UTC, blackfalcon commented on package.json
> +  "version": "2.0.4",
We never update the package.json version in a PR, this is an automated task.

2024-05-07 22:40 UTC, blackfalcon commented on test/auro-card.test.js
> +          src="https://images.contentstack.io/v3/assets/blt2cefe12c88e9dd91/bltab511d45f1fb699d/6633f79881836880d9fc1424/blue.png"
This image issue was resolved with the new version being released soon.

2024-06-12 16:57 UTC, Patrick-Daly-AA commented
@braven112 please confirm if this is still needed with the 2.0 release.  From talking about this at standup, we don't think these changes are valid anymore.

2025-04-03 05:56 UTC, closed without merging